/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeusPedidosRouteImport } from './routes/meus-pedidos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CuponsRouteImport } from './routes/cupons'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected.admin.index'
import { Route as ProtectedAdminProdutosRouteImport } from './routes/_protected.admin.produtos'
import { Route as ProtectedAdminPizzasRouteImport } from './routes/_protected.admin.pizzas'
import { Route as ProtectedAdminPedidosRouteImport } from './routes/_protected.admin.pedidos'
import { Route as ProtectedAdminMarketingRouteImport } from './routes/_protected.admin.marketing'
import { Route as ProtectedAdminEquipeRouteImport } from './routes/_protected.admin.equipe'
import { Route as ProtectedAdminConfiguracoesRouteImport } from './routes/_protected.admin.configuracoes'
import { Route as ProtectedAdminClientesRouteImport } from './routes/_protected.admin.clientes'
import { Route as ProtectedAdminCategoriasRouteImport } from './routes/_protected.admin.categorias'

const MeusPedidosRoute = MeusPedidosRouteImport.update({
  id: '/meus-pedidos',
  path: '/meus-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CuponsRoute = CuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminProdutosRoute = ProtectedAdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPizzasRoute = ProtectedAdminPizzasRouteImport.update({
  id: '/admin/pizzas',
  path: '/admin/pizzas',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPedidosRoute = ProtectedAdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminMarketingRoute = ProtectedAdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminEquipeRoute = ProtectedAdminEquipeRouteImport.update({
  id: '/admin/equipe',
  path: '/admin/equipe',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminConfiguracoesRoute =
  ProtectedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminClientesRoute = ProtectedAdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminCategoriasRoute =
  ProtectedAdminCategoriasRouteImport.update({
    id: '/admin/categorias',
    path: '/admin/categorias',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cupons': typeof CuponsRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/admin/categorias': typeof ProtectedAdminCategoriasRoute
  '/admin/clientes': typeof ProtectedAdminClientesRoute
  '/admin/configuracoes': typeof ProtectedAdminConfiguracoesRoute
  '/admin/equipe': typeof ProtectedAdminEquipeRoute
  '/admin/marketing': typeof ProtectedAdminMarketingRoute
  '/admin/pedidos': typeof ProtectedAdminPedidosRoute
  '/admin/pizzas': typeof ProtectedAdminPizzasRoute
  '/admin/produtos': typeof ProtectedAdminProdutosRoute
  '/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cupons': typeof CuponsRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/admin/categorias': typeof ProtectedAdminCategoriasRoute
  '/admin/clientes': typeof ProtectedAdminClientesRoute
  '/admin/configuracoes': typeof ProtectedAdminConfiguracoesRoute
  '/admin/equipe': typeof ProtectedAdminEquipeRoute
  '/admin/marketing': typeof ProtectedAdminMarketingRoute
  '/admin/pedidos': typeof ProtectedAdminPedidosRoute
  '/admin/pizzas': typeof ProtectedAdminPizzasRoute
  '/admin/produtos': typeof ProtectedAdminProdutosRoute
  '/admin': typeof ProtectedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/cupons': typeof CuponsRoute
  '/login': typeof LoginRoute
  '/meus-pedidos': typeof MeusPedidosRoute
  '/_protected/admin/categorias': typeof ProtectedAdminCategoriasRoute
  '/_protected/admin/clientes': typeof ProtectedAdminClientesRoute
  '/_protected/admin/configuracoes': typeof ProtectedAdminConfiguracoesRoute
  '/_protected/admin/equipe': typeof ProtectedAdminEquipeRoute
  '/_protected/admin/marketing': typeof ProtectedAdminMarketingRoute
  '/_protected/admin/pedidos': typeof ProtectedAdminPedidosRoute
  '/_protected/admin/pizzas': typeof ProtectedAdminPizzasRoute
  '/_protected/admin/produtos': typeof ProtectedAdminProdutosRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cupons'
    | '/login'
    | '/meus-pedidos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/pizzas'
    | '/admin/produtos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cupons'
    | '/login'
    | '/meus-pedidos'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/admin/marketing'
    | '/admin/pedidos'
    | '/admin/pizzas'
    | '/admin/produtos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/cupons'
    | '/login'
    | '/meus-pedidos'
    | '/_protected/admin/categorias'
    | '/_protected/admin/clientes'
    | '/_protected/admin/configuracoes'
    | '/_protected/admin/equipe'
    | '/_protected/admin/marketing'
    | '/_protected/admin/pedidos'
    | '/_protected/admin/pizzas'
    | '/_protected/admin/produtos'
    | '/_protected/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CuponsRoute: typeof CuponsRoute
  LoginRoute: typeof LoginRoute
  MeusPedidosRoute: typeof MeusPedidosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meus-pedidos': {
      id: '/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof MeusPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupons': {
      id: '/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof CuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/produtos': {
      id: '/_protected/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof ProtectedAdminProdutosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/pizzas': {
      id: '/_protected/admin/pizzas'
      path: '/admin/pizzas'
      fullPath: '/admin/pizzas'
      preLoaderRoute: typeof ProtectedAdminPizzasRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/pedidos': {
      id: '/_protected/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof ProtectedAdminPedidosRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/marketing': {
      id: '/_protected/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof ProtectedAdminMarketingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/equipe': {
      id: '/_protected/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof ProtectedAdminEquipeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/configuracoes': {
      id: '/_protected/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof ProtectedAdminConfiguracoesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/clientes': {
      id: '/_protected/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof ProtectedAdminClientesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/categorias': {
      id: '/_protected/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof ProtectedAdminCategoriasRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminCategoriasRoute: typeof ProtectedAdminCategoriasRoute
  ProtectedAdminClientesRoute: typeof ProtectedAdminClientesRoute
  ProtectedAdminConfiguracoesRoute: typeof ProtectedAdminConfiguracoesRoute
  ProtectedAdminEquipeRoute: typeof ProtectedAdminEquipeRoute
  ProtectedAdminMarketingRoute: typeof ProtectedAdminMarketingRoute
  ProtectedAdminPedidosRoute: typeof ProtectedAdminPedidosRoute
  ProtectedAdminPizzasRoute: typeof ProtectedAdminPizzasRoute
  ProtectedAdminProdutosRoute: typeof ProtectedAdminProdutosRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminCategoriasRoute: ProtectedAdminCategoriasRoute,
  ProtectedAdminClientesRoute: ProtectedAdminClientesRoute,
  ProtectedAdminConfiguracoesRoute: ProtectedAdminConfiguracoesRoute,
  ProtectedAdminEquipeRoute: ProtectedAdminEquipeRoute,
  ProtectedAdminMarketingRoute: ProtectedAdminMarketingRoute,
  ProtectedAdminPedidosRoute: ProtectedAdminPedidosRoute,
  ProtectedAdminPizzasRoute: ProtectedAdminPizzasRoute,
  ProtectedAdminProdutosRoute: ProtectedAdminProdutosRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  CuponsRoute: CuponsRoute,
  LoginRoute: LoginRoute,
  MeusPedidosRoute: MeusPedidosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
